### Authentication

@hostname=localhost
@port=5000
@host={{hostname}}:{{port}}
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzg5MjAzMTU1LCJleHAiOjE3ODkyMDY3NTV9.iZeg43odwmBZPKh_md_mVQ94_74w8P32iyaJMdtoAFU

### Login
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password"
}

### Register
POST http://{{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password",
  "name": "User Name"
}

### Get Current User   
GET http://{{host}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}