### Authentication

@hostname=localhost
@port=5000
@host={{hostname}}:{{port}}
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwiaWF0IjoxNzg5MzkxNjkxLCJleHAiOjE3ODkzOTUyOTF9.UiDqhXf8lvpbhvQzRCbOPj37qGEWfjhR1vVph7YG2Ig
@refreshToken=b3061832d470d1a8eb4872bed46c0adae3e3e2f0c8e21e02c0d6003903650553f72a015bc803867d27424ee56d3090548c1c5b54917d7828cc6831da71c9070c

### Login
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "password123"
}

### Register
POST http://{{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password",
  "name": "User1 Name1"
}

### Refresh Token
POST http://{{host}}/api/auth/refresh
Content-Type: application/json

{
"refreshToken": "{{refreshToken}}"
}

### Get Current User   
GET http://{{host}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Logout
POST http://{{host}}/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}